# sudo docker compose -f docker/postgres_only/docker-compose.yaml up
services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  adminer:
    # visit http://localhost:8080/?pgsql=db. 
    # Notice:  
    # select system as PostgreSQL
    # the server name should be "db" which matches the name defined above.
    # the database should be "myapp".
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data: