# sudo docker compose -f docker/postgres_with_jaeger/docker-compose.yaml up
services:
  jaeger:
    # visit http://localhost:16686/search
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    depends_on:
      - db

  adminer:
    # visit http://localhost:8080/?pgsql=db. 
    # Notice:  
    # select system as PostgreSQL
    # the server name should be "db" which matches the name defined above.
    # the database should be "myapp".
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_with_jaeger
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


# Error response from daemon: Conflict. The container name "/jaeger" is already in use by container
# Solution: sudo docker rm jaeger