//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    async_graphql :: SimpleObject,
)]
#[sea_orm(table_name = "key_feature")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::milestone_keyfeature::Entity")]
    MilestoneKeyfeature,
    #[sea_orm(has_many = "super::storage_type_keyfeature::Entity")]
    StorageTypeKeyfeature,
    #[sea_orm(has_many = "super::workload_keyfeature::Entity")]
    WorkloadKeyfeature,
}

impl Related<super::milestone_keyfeature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MilestoneKeyfeature.def()
    }
}

impl Related<super::storage_type_keyfeature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StorageTypeKeyfeature.def()
    }
}

impl Related<super::workload_keyfeature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkloadKeyfeature.def()
    }
}

impl Related<super::milestone::Entity> for Entity {
    fn to() -> RelationDef {
        super::milestone_keyfeature::Relation::Milestone.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::milestone_keyfeature::Relation::KeyFeature
                .def()
                .rev(),
        )
    }
}

impl Related<super::storage_type::Entity> for Entity {
    fn to() -> RelationDef {
        super::storage_type_keyfeature::Relation::StorageType.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::storage_type_keyfeature::Relation::KeyFeature
                .def()
                .rev(),
        )
    }
}

impl Related<super::workload::Entity> for Entity {
    fn to() -> RelationDef {
        super::workload_keyfeature::Relation::Workload.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::workload_keyfeature::Relation::KeyFeature.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
