//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    async_graphql :: SimpleObject,
)]
#[sea_orm(table_name = "storage_type")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::storage_type_keyfeature::Entity")]
    StorageTypeKeyfeature,
    #[sea_orm(has_many = "super::workload::Entity")]
    Workload,
}

impl Related<super::storage_type_keyfeature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StorageTypeKeyfeature.def()
    }
}

impl Related<super::workload::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workload.def()
    }
}

impl Related<super::key_feature::Entity> for Entity {
    fn to() -> RelationDef {
        super::storage_type_keyfeature::Relation::KeyFeature.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::storage_type_keyfeature::Relation::StorageType
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
