//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    async_graphql :: SimpleObject,
)]
#[sea_orm(table_name = "workload")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub storage_type_id: Option<i32>,
    pub status: String,
    pub release_version: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::storage_type::Entity",
        from = "Column::StorageTypeId",
        to = "super::storage_type::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    StorageType,
    #[sea_orm(has_many = "super::workload_keyfeature::Entity")]
    WorkloadKeyfeature,
}

impl Related<super::storage_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::StorageType.def()
    }
}

impl Related<super::workload_keyfeature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkloadKeyfeature.def()
    }
}

impl Related<super::key_feature::Entity> for Entity {
    fn to() -> RelationDef {
        super::workload_keyfeature::Relation::KeyFeature.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::workload_keyfeature::Relation::Workload.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
