//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    async_graphql :: SimpleObject,
)]
#[sea_orm(table_name = "workload_keyfeature")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub workload_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub keyfeature_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::key_feature::Entity",
        from = "Column::KeyfeatureId",
        to = "super::key_feature::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    KeyFeature,
    #[sea_orm(
        belongs_to = "super::workload::Entity",
        from = "Column::WorkloadId",
        to = "super::workload::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Workload,
}

impl Related<super::key_feature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::KeyFeature.def()
    }
}

impl Related<super::workload::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workload.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
